### ISSUE TITLE
Error message when saving settings

### ISSUE THREAD

**Issue by xkevinx** [friday/ulauncher-clipboard#30]
Hi!

I got this error message every time I try to save settings updates:

```
Message: 'com.github.friday.ulauncher-clipboard'
Error Name: UnhandledError
Type: KeyError

Stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 202, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 456, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.friday.ulauncher-clipboard'

```

![Screenshot from 2021-11-13 21-56-43](https://user-images.githubusercontent.com/22234781/141646686-701ba8b0-5b24-4620-bd45-9cac548bf77e.png)

I'm trying to set the clipboard manager to CopyQ instead of Auto because it ulauncher doesn't seem to be able to find my clipboard history.

thanks!

**Comment by friday** [comment]
This is a Ulauncher issue that some people reported, but I haven't been able to replicate it. Sometimes it happens becalming of missing dependencies and sometimes for invalid reasons. It's probably fixed in the v6 branch that will be the next major Ulauncher version.
