### ISSUE TITLE
Clipboard extension doesn't work since update to ubuntu 21.10

### ISSUE THREAD

**Issue by mihani** [friday/ulauncher-clipboard#32]
In ubuntu 20.04 I didn't have problem. After dist-upgrade from 20.04 to 21.10, clipboard extension didn't work. I try after restart but didn't work. I try too uninstall/install extension but same issue.
I already use with gpaste and it works when I used it standalone. I try with copyq too but doesn't work too.

Distro ubuntu 21.10 - gnome 40

Log when I trigger keyword to open clipboard addon on ulauncher
```
com.github.friday.ulauncher-clipboard | 2022-01-05 18:50:57,280 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event KeywordQueryEvent
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'get_filename'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3/dist-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
  File "/home/rmaud/.local/share/ulauncher/extensions/com.github.friday.ulauncher-clipboard/main.py", line 89, in on_event
    icon = getThemeIcon('edit-paste', 32)
  File "/home/rmaud/.local/share/ulauncher/extensions/com.github.friday.ulauncher-clipboard/lib.py", line 40, in getThemeIcon
    return execGet(sys.executable, '-c', "import gi; gi.require_version('Gtk', '3.0'); from gi.repository import Gtk; print({})".format(getIconCode))
  File "/home/rmaud/.local/share/ulauncher/extensions/com.github.friday.ulauncher-clipboard/lib.py", line 21, in execGet
    return subprocess.check_output(list(args)).rstrip().decode('utf-8')
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-c', "import gi; gi.require_version('Gtk', '3.0'); from gi.repository import Gtk; print(Gtk.IconTheme.get_default().lookup_icon('edit-paste', 32, 0).get_filename())"]' returned non-zero exit status 1.
```
Ask me if you have more questions

**Comment by friday** [comment]
You probably need to install an icon theme. And this whole workaround won't be needed in the next major Ulauncher version.

**Comment by friday** [comment]
Should be fixed now
